#!name=美图
#!desc=美图系列VIP
#!author=chxm1023 ikun
#!icon=https://raw.githubusercontent.com/Orz-3/mini/master/Alpha/Dukou.png

[Script]
# 美图秀秀
mt = type=http-response, pattern=^https?:\/\/((h5|api)\.xiuxiu|api-sub|api\.posters)\.meitu\.com\/.+\/(vip|user|h\d|center|home), script-path=https://raw.githubusercontent.com/onenora/saber/main/scripts/mt.js, requires-body=true, max-size=-1, timeout=60

# 美图子应用 (Wink等)
mt = type=http-response, pattern=^https:\/\/api-.*\.meitu\.com\/(.+\/user\/vip_info|user\/show), script-path=https://raw.githubusercontent.com/onenora/saber/main/scripts/mt.js, requires-body=true, max-size=-1, timeout=60

[MITM]
hostname = %APPEND% *.xiuxiu.meitu.com, api.posters.meitu.com, api-*.meitu.com